version: "3.8"
services:
  client:
    build: ./client
    container_name: client_container
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    command: sh -c "npm rebuild esbuild && npm run dev"
